Implement delete cluster by name action
realm/ci-actions pull request #10
Opened 2022-07-05 11:57 UTC by desistefanova

Deletes a cluster by given specific name.

2022-08-01 09:36 UTC, nirinchev requested changes
Do we need this? I guess most of this functionality is covered by the cleanup action - the only difference is that it also deletes the applications for that cluster. Is there a case where you only want to delete the cluster but not the apps?

2022-08-01 09:36 UTC, nirinchev commented on mdb-realm/deleteCluster/action.yml
> +    description: Provide a specific name of cluster that to be deleted."
```suggestion
    description: Provide a specific name of cluster that to be deleted.
```

2022-11-05 06:10 UTC, desistefanova commented
> Do we need this? I guess most of this functionality is covered by the cleanup action - the only difference is that it also deletes the applications for that cluster. Is there a case where you only want to delete the cluster but not the apps?

Yes @nirinchev, we delete the cluster and the apps at the end of the workflow. The only thing that cleanup and deleteAllClusters are missing is the parameter clusterName. They both don't support deleting a specific cluster. They will delete all the clusters for all the running CIs in this project. We are running all the PR's CIs in the same project.
BTW, What is the difference between cleanup and deleteAllClusters? It looks they are doing the same thing.

2022-11-06 12:39 UTC, nirinchev commented
cleanup calls `getConfig`, which will get the cluster name if provided as an argument: https://github.com/realm/ci-actions/blob/0101f67e2a3cc2e1f46087f8264edc7ef0aa4aa3/mdb-realm/src/helpers.ts#L23. It looks like we should add it to the action.yml here: https://github.com/realm/ci-actions/blob/0101f67e2a3cc2e1f46087f8264edc7ef0aa4aa3/mdb-realm/cleanup/action.yml#L4 and it should just work. `deleteAllClusters` deletes all clusters, not an individual one.

2022-11-06 12:58 UTC, desistefanova commented
> > Do we need this? I guess most of this functionality is covered by the cleanup action - the only difference is that it also deletes the applications for that cluster. Is there a case where you only want to delete the cluster but not the apps?
> 
> Yes @nirinchev, we delete the cluster and the apps at the end of the workflow. The only thing that cleanup and deleteAllClusters are missing is the parameter clusterName. They both don't support deleting a specific cluster. They will delete all the clusters for all the running CIs in this project. We are running all the PR's CIs in the same project. BTW, What is the difference between cleanup and deleteAllClusters? It looks they are doing the same thing.

@nirinchev OK, I can do that and then I will close this PR.

2022-11-07 09:43 UTC, desistefanova commented
> Done in #19

2022-11-07 12:38 UTC, desistefanova commented
Moved to https://github.com/realm/ci-actions/pull/19

2022-11-07 12:38 UTC, closed without merging